export const UPDATE_PRODUCT_GROUP = 'UPDATE_PRODUCT_GROUP'
export const UPDATE_BRANDS = 'UPDATE_BRANDS'
export const UPDATE_MANUFACTURERS = 'UPDATE_MANUFACTURERS'
export const SET_SIDE_BAR_STATUS = 'SET_SIDE_BAR_STATUS'
