export const SET_GROUP_NAME = 'SET_GROUP_NAME'
export const SET_GROUP_ATTRIBUTE = 'SET_GROUP_ATTRIBUTE'
export const POPULATE_EXISTING_GROUP_ATTRIBUTES = 'POPULATE_EXISTING_GROUP_ATTRIBUTES'
export const SET_GROUP_ERRORS = 'SET_GROUP_ERRORS'
