name: Deploy App
on:
  push:
    branches:
      - master
jobs:
  auto-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            cd /var/www/html/product-listing-frontend
            git pull origin master
            # npm install
            # npm run build
